import type { Product, Project, FAQItem, Category } from '@/types'

export const mockProducts: Product[] = [
  {
    id: 'mock-1',
    slug: 'mesa-industrial-hierro-madera',
    sku: 'IP-MES-001',
    name: 'Mesa Industrial Hierro y Madera',
    shortDescription: 'Mesa comedor con estructura de hierro negro y tablero de madera maciza. Ideal para living o comedor.',
    seoTitle: 'Mesa Industrial Hierro y Madera | Iron Project',
    seoDescription: 'Mesa comedor con estructura de hierro negro y tablero de madera maciza. Fabricación artesanal, entrega 5-7 días.',
    category: 'hogar',
    subcategory: 'mesas',
    tags: ['mesa', 'hierro', 'madera', 'industrial', 'comedor'],
    images: [
      {
        url: '/images/producto-1.jpg',
        alt: 'Mesa Industrial Hierro y Madera',
        order: 0,
      },
      {
        url: '/images/producto-2.jpg',
        alt: 'Detalle pata mesa industrial',
        order: 1,
      },
    ],
    pricing: {
      basePrice: 85000,
      customPrice: 120000,
      wholesalePrice: 70000,
      wholesaleMinQty: 5,
      currency: 'ARS',
    },
    variants: {
      sizes: [
        { label: '120x70 cm', value: '120x70', priceModifier: 0 },
        { label: '150x80 cm', value: '150x80', priceModifier: 15000 },
        { label: '180x90 cm', value: '180x90', priceModifier: 30000 },
      ],
      colors: [
        { label: 'Negro Mate', value: 'negro-mate', hex: '#1a1a1a' },
        { label: 'Negro Satinado', value: 'negro-satinado', hex: '#2d2d2d' },
        { label: 'Óxido', value: 'oxido', hex: '#8b4513' },
      ],
      materials: [
        { label: 'Madera Pino', value: 'pino', priceModifier: 0 },
        { label: 'Madera Roble', value: 'roble', priceModifier: 20000 },
        { label: 'Vidrio Templado', value: 'vidrio', priceModifier: 25000 },
      ],
      customSizeAvailable: true,
    },
    specs: {
      materials: ['Hierro estructural 40x40mm', 'Madera maciza pino'],
      dimensions: '120x70x75 cm (estándar)',
      weight: '35 kg',
      leadTime: '5-7 días hábiles',
      shippingAvailable: true,
    },
    flags: {
      isFeatured: true,
      isNew: false,
      isCustomizable: true,
      isWholesaleAvailable: true,
      isActive: true,
    },
    relatedProducts: ['mock-2', 'mock-3'],
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'mock-2',
    slug: 'escritorio-industrial-hierro',
    sku: 'IP-ESC-001',
    name: 'Escritorio Industrial con Estante',
    shortDescription: 'Escritorio de trabajo con estructura de hierro y estante superior. Perfecto para home office con estilo.',
    seoTitle: 'Escritorio Industrial con Estante | Iron Project',
    seoDescription: 'Escritorio de trabajo con estructura de hierro y estante superior. Fabricación artesanal a medida.',
    category: 'hogar',
    subcategory: 'escritorios',
    tags: ['escritorio', 'hierro', 'home office', 'industrial'],
    images: [
      {
        url: '/images/producto-2.jpg',
        alt: 'Escritorio Industrial con Estante',
        order: 0,
      },
    ],
    pricing: {
      basePrice: 65000,
      customPrice: 95000,
      wholesalePrice: 55000,
      wholesaleMinQty: 3,
      currency: 'ARS',
    },
    variants: {
      sizes: [
        { label: '120x60 cm', value: '120x60', priceModifier: 0 },
        { label: '140x70 cm', value: '140x70', priceModifier: 10000 },
        { label: '160x70 cm', value: '160x70', priceModifier: 20000 },
      ],
      colors: [
        { label: 'Negro Mate', value: 'negro-mate', hex: '#1a1a1a' },
        { label: 'Negro Satinado', value: 'negro-satinado', hex: '#2d2d2d' },
      ],
      materials: [
        { label: 'Madera Pino', value: 'pino', priceModifier: 0 },
        { label: 'Madera Roble', value: 'roble', priceModifier: 15000 },
      ],
      customSizeAvailable: true,
    },
    specs: {
      materials: ['Hierro estructural 30x30mm', 'Madera maciza pino'],
      dimensions: '120x60x75 cm (estándar)',
      weight: '22 kg',
      leadTime: '5-7 días hábiles',
      shippingAvailable: true,
    },
    flags: {
      isFeatured: true,
      isNew: true,
      isCustomizable: true,
      isWholesaleAvailable: false,
      isActive: true,
    },
    relatedProducts: ['mock-1'],
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2024-03-05T00:00:00Z',
  },
  {
    id: 'mock-3',
    slug: 'arco-decorativo-eventos',
    sku: 'IP-ARC-001',
    name: 'Arco Decorativo para Eventos',
    shortDescription: 'Arco de hierro para decoración de eventos, bodas y celebraciones. Desmontable y fácil de transportar.',
    seoTitle: 'Arco Decorativo para Eventos | Iron Project',
    seoDescription: 'Arco de hierro desmontable para decoración de eventos y bodas. Alquiler y venta disponible.',
    category: 'eventos',
    subcategory: 'arcos',
    tags: ['arco', 'eventos', 'bodas', 'decoración', 'hierro'],
    images: [
      {
        url: '/images/producto-1.jpg',
        alt: 'Arco Decorativo para Eventos',
        order: 0,
      },
    ],
    pricing: {
      basePrice: 45000,
      customPrice: 70000,
      wholesalePrice: 38000,
      wholesaleMinQty: 10,
      currency: 'ARS',
    },
    variants: {
      sizes: [
        { label: '2x2 m', value: '2x2', priceModifier: 0 },
        { label: '2.5x2.5 m', value: '2.5x2.5', priceModifier: 8000 },
        { label: '3x3 m', value: '3x3', priceModifier: 15000 },
      ],
      colors: [
        { label: 'Negro Mate', value: 'negro-mate', hex: '#1a1a1a' },
        { label: 'Dorado', value: 'dorado', hex: '#D4A853' },
        { label: 'Blanco', value: 'blanco', hex: '#f6f6f6' },
      ],
      materials: [
        { label: 'Hierro estándar', value: 'estandar', priceModifier: 0 },
      ],
      customSizeAvailable: true,
    },
    specs: {
      materials: ['Hierro cuadrado 20x20mm'],
      dimensions: '200x200 cm (estándar)',
      weight: '18 kg',
      leadTime: '3-5 días hábiles',
      shippingAvailable: true,
    },
    flags: {
      isFeatured: true,
      isNew: false,
      isCustomizable: true,
      isWholesaleAvailable: true,
      isActive: true,
    },
    relatedProducts: ['mock-4'],
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
  },
  {
    id: 'mock-4',
    slug: 'fondo-backdrop-metalico',
    sku: 'IP-FON-001',
    name: 'Fondo Metálico para Eventos',
    shortDescription: 'Estructura metálica tipo backdrop para decoración de eventos y fotografía. Versátil y elegante.',
    seoTitle: 'Fondo Metálico para Eventos | Iron Project',
    seoDescription: 'Estructura metálica tipo backdrop para decoración de eventos y fotografía. Fabricación a medida.',
    category: 'eventos',
    subcategory: 'fondos',
    tags: ['fondo', 'backdrop', 'eventos', 'fotografía', 'hierro'],
    images: [
      {
        url: '/images/producto-2.jpg',
        alt: 'Fondo Metálico para Eventos',
        order: 0,
      },
    ],
    pricing: {
      basePrice: 38000,
      customPrice: 60000,
      wholesalePrice: 32000,
      wholesaleMinQty: 5,
      currency: 'ARS',
    },
    variants: {
      sizes: [
        { label: '2x2 m', value: '2x2', priceModifier: 0 },
        { label: '2x2.5 m', value: '2x2.5', priceModifier: 6000 },
        { label: '3x2.5 m', value: '3x2.5', priceModifier: 12000 },
      ],
      colors: [
        { label: 'Negro Mate', value: 'negro-mate', hex: '#1a1a1a' },
        { label: 'Dorado', value: 'dorado', hex: '#D4A853' },
      ],
      materials: [
        { label: 'Hierro estándar', value: 'estandar', priceModifier: 0 },
      ],
      customSizeAvailable: true,
    },
    specs: {
      materials: ['Hierro redondo 16mm'],
      dimensions: '200x200 cm (estándar)',
      weight: '12 kg',
      leadTime: '3-5 días hábiles',
      shippingAvailable: true,
    },
    flags: {
      isFeatured: false,
      isNew: true,
      isCustomizable: true,
      isWholesaleAvailable: true,
      isActive: true,
    },
    relatedProducts: ['mock-3'],
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-10T00:00:00Z',
  },
  {
    id: 'mock-5',
    slug: 'exhibidor-ropa-comercial',
    sku: 'IP-EXH-001',
    name: 'Exhibidor de Ropa Industrial',
    shortDescription: 'Exhibidor de ropa con estructura de hierro para locales comerciales. Minimalista y funcional.',
    seoTitle: 'Exhibidor de Ropa Industrial | Iron Project',
    seoDescription: 'Exhibidor de ropa con estructura de hierro para locales comerciales. Fabricación en serie y a medida.',
    category: 'comercial',
    subcategory: 'exhibidores',
    tags: ['exhibidor', 'ropa', 'local', 'comercial', 'hierro'],
    images: [
      {
        url: '/images/producto-1.jpg',
        alt: 'Exhibidor de Ropa Industrial',
        order: 0,
      },
    ],
    pricing: {
      basePrice: 28000,
      customPrice: 42000,
      wholesalePrice: 22000,
      wholesaleMinQty: 10,
      currency: 'ARS',
    },
    variants: {
      sizes: [
        { label: '90x150 cm', value: '90x150', priceModifier: 0 },
        { label: '120x180 cm', value: '120x180', priceModifier: 5000 },
        { label: '150x180 cm', value: '150x180', priceModifier: 10000 },
      ],
      colors: [
        { label: 'Negro Mate', value: 'negro-mate', hex: '#1a1a1a' },
        { label: 'Negro Satinado', value: 'negro-satinado', hex: '#2d2d2d' },
        { label: 'Blanco', value: 'blanco', hex: '#f6f6f6' },
      ],
      materials: [
        { label: 'Hierro estándar', value: 'estandar', priceModifier: 0 },
      ],
      customSizeAvailable: true,
    },
    specs: {
      materials: ['Hierro cuadrado 20x20mm', 'Hierro redondo 12mm'],
      dimensions: '90x40x150 cm (estándar)',
      weight: '8 kg',
      leadTime: '3-5 días hábiles',
      shippingAvailable: true,
    },
    flags: {
      isFeatured: true,
      isNew: false,
      isCustomizable: true,
      isWholesaleAvailable: true,
      isActive: true,
    },
    relatedProducts: ['mock-6'],
    createdAt: '2024-01-25T00:00:00Z',
    updatedAt: '2024-02-20T00:00:00Z',
  },
  {
    id: 'mock-6',
    slug: 'estanteria-comercial-hierro',
    sku: 'IP-EST-001',
    name: 'Estantería Comercial de Hierro',
    shortDescription: 'Estantería industrial para locales comerciales. Resistente, modular y de gran presencia visual.',
    seoTitle: 'Estantería Comercial de Hierro | Iron Project',
    seoDescription: 'Estantería industrial para locales comerciales. Modular, resistente y personalizable a medida.',
    category: 'comercial',
    subcategory: 'estanterias',
    tags: ['estantería', 'comercial', 'local', 'industrial', 'modular'],
    images: [
      {
        url: '/images/producto-2.jpg',
        alt: 'Estantería Comercial de Hierro',
        order: 0,
      },
    ],
    pricing: {
      basePrice: 55000,
      customPrice: 80000,
      wholesalePrice: 45000,
      wholesaleMinQty: 5,
      currency: 'ARS',
    },
    variants: {
      sizes: [
        { label: '90x30x180 cm (3 estantes)', value: '90x30x180-3', priceModifier: 0 },
        { label: '120x35x200 cm (4 estantes)', value: '120x35x200-4', priceModifier: 15000 },
        { label: '150x40x220 cm (5 estantes)', value: '150x40x220-5', priceModifier: 30000 },
      ],
      colors: [
        { label: 'Negro Mate', value: 'negro-mate', hex: '#1a1a1a' },
        { label: 'Negro Satinado', value: 'negro-satinado', hex: '#2d2d2d' },
        { label: 'Óxido', value: 'oxido', hex: '#8b4513' },
      ],
      materials: [
        { label: 'Solo hierro', value: 'hierro', priceModifier: 0 },
        { label: 'Hierro + Madera', value: 'hierro-madera', priceModifier: 12000 },
        { label: 'Hierro + Vidrio', value: 'hierro-vidrio', priceModifier: 18000 },
      ],
      customSizeAvailable: true,
    },
    specs: {
      materials: ['Hierro estructural 40x40mm', 'Chapa plana para estantes'],
      dimensions: '90x30x180 cm (estándar)',
      weight: '45 kg',
      leadTime: '7-10 días hábiles',
      shippingAvailable: true,
    },
    flags: {
      isFeatured: true,
      isNew: false,
      isCustomizable: true,
      isWholesaleAvailable: true,
      isActive: true,
    },
    relatedProducts: ['mock-5'],
    createdAt: '2024-02-05T00:00:00Z',
    updatedAt: '2024-03-08T00:00:00Z',
  },
]

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    slug: 'decoracion-salon-bodas-nordelta',
    title: 'Salón de Bodas — Nordelta',
    description: 'Decoramos un completo salón de eventos con arcos, fondos y estructuras de hierro. Más de 20 piezas personalizadas para una boda de 200 personas.',
    category: 'eventos',
    images: [
      {
        url: '/images/producto-1.jpg',
        alt: 'Salón de Bodas Nordelta',
        order: 0,
      },
    ],
    isB2B: true,
    clientName: 'Salón La Pampa',
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'proj-2',
    slug: 'local-indumentaria-palermo',
    title: 'Local de Indumentaria — Palermo',
    description: 'Equipamos un local de ropa en Palermo con exhibidores, percheros y estanterías de hierro. Diseño minimalista industrial para una marca premium.',
    category: 'comercial',
    images: [
      {
        url: '/images/producto-2.jpg',
        alt: 'Local de Indumentaria Palermo',
        order: 0,
      },
    ],
    isB2B: true,
    clientName: 'Marca Confidencial',
    createdAt: '2024-02-15T00:00:00Z',
  },
  {
    id: 'proj-3',
    slug: 'departamento-san-telmo',
    title: 'Departamento — San Telmo',
    description: 'Muebles a medida para un departamento en San Telmo. Mesa comedor, escritorio y estantes de hierro con madera reciclada.',
    category: 'hogar',
    images: [
      {
        url: '/images/producto-1.jpg',
        alt: 'Departamento San Telmo',
        order: 0,
      },
    ],
    isB2B: false,
    createdAt: '2024-01-20T00:00:00Z',
  },
]

export const mockFAQs: FAQItem[] = [
  {
    id: 'faq-1',
    question: '¿Cuánto tiempo tarda la fabricación?',
    answer: 'La mayoría de nuestros productos se fabrican en 5 a 7 días hábiles. Para pedidos personalizados o de gran volumen, el plazo puede extenderse a 10-15 días. Siempre te confirmamos el plazo exacto al momento del pedido.',
    category: 'fabricacion',
  },
  {
    id: 'faq-2',
    question: '¿Hacen envíos a todo el país?',
    answer: 'Sí, enviamos a todo el país. Para CABA y GBA hacemos entregas propias (más económico y seguro). Para el interior, trabajamos con transportes de confianza. El costo de envío se calcula según el destino y el volumen del pedido.',
    category: 'envios',
  },
  {
    id: 'faq-3',
    question: '¿Puedo pedir una medida personalizada?',
    answer: 'Absolutamente. Casi todos nuestros productos son personalizables en medidas. Solo necesitás contarnos el espacio que tenés disponible y te diseñamos la pieza perfecta. Sin costo adicional por la consulta.',
    category: 'personalizacion',
  },
  {
    id: 'faq-4',
    question: '¿Cuáles son los precios? ¿Están actualizados?',
    answer: 'Los precios del catálogo son orientativos y se actualizan regularmente. Para obtener el precio final (con tu medida, color y acabado elegido) lo mejor es consultarnos por WhatsApp. Respondemos en menos de 1 hora en horario comercial.',
    category: 'precios',
  },
  {
    id: 'faq-5',
    question: '¿Tienen precios mayoristas para negocios?',
    answer: 'Sí. Trabajamos con locales de decoración, event planners, fotógrafos y empresas que necesitan varias unidades. Ofrecemos precios especiales a partir de 3-5 unidades según el producto. Consultanos para armar una cotización.',
    category: 'mayoristas',
  },
]

export const mockCategories: Category[] = [
  {
    id: 'cat-hogar',
    slug: 'hogar',
    name: 'Hogar',
    description: 'Mesas, escritorios, estantes y muebles con estilo industrial para tu hogar.',
    image: {
      url: '/images/producto-1.jpg',
      alt: 'Muebles de hierro para el hogar',
      order: 0,
    },
    subcategories: [
      { label: 'Mesas', value: 'mesas' },
      { label: 'Escritorios', value: 'escritorios' },
      { label: 'Estantes', value: 'estantes' },
      { label: 'Percheros', value: 'percheros' },
    ],
  },
  {
    id: 'cat-eventos',
    slug: 'eventos',
    name: 'Eventos',
    description: 'Arcos, fondos y estructuras decorativas para bodas, fiestas y eventos especiales.',
    image: {
      url: '/images/producto-1.jpg',
      alt: 'Estructuras de hierro para eventos',
      order: 0,
    },
    subcategories: [
      { label: 'Arcos', value: 'arcos' },
      { label: 'Fondos', value: 'fondos' },
      { label: 'Estructuras', value: 'estructuras' },
    ],
  },
  {
    id: 'cat-comercial',
    slug: 'comercial',
    name: 'Comercial',
    description: 'Exhibidores, estanterías y mobiliario industrial para locales y negocios.',
    image: {
      url: '/images/producto-2.jpg',
      alt: 'Muebles de hierro para locales comerciales',
      order: 0,
    },
    subcategories: [
      { label: 'Exhibidores', value: 'exhibidores' },
      { label: 'Estanterías', value: 'estanterias' },
      { label: 'Percheros', value: 'percheros' },
    ],
  },
]
